# docker-compose.yml (Production - base file)
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
      - "9222:9222"  # Chrome DevTools
      - "9229:9229"  # Node.js debugger
    depends_on:
      - webapp
      - server

  webapp:
    build: ./webapp
    environment:
      - API_URL=/api/v1
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-random}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  server:
    build: ./server
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=app
      - JWT_SECRET=asfasfsasdiojo
      - JWT_EXPIRES_IN=1h
    depends_on:
      - mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=app
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  mongodb_data: