services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp
      - NODE_ENV=production
      - JWT_SECRET=random
    depends_on:
      - db
    restart: always