services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
      - "9222:9222"  # Chrome DevTools
      - "9229:9229"  # Node.js debugger
    depends_on:
      - webapp
      - server

  webapp:
    ports: []
    build:
      context: ./webapp
      target: deps
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./webapp:/app:rw
      - webapp_node_modules:/app/node_modules:rw

  server:
    ports: []
    build:
      context: ./server
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    command: npm run dev
    volumes:
      - ./server:/app:rw
      - server_node_modules:/app/node_modules:rw

  qa:
    build:
      context: ./qa
    privileged: true 
    volumes:
      - ./qa:/app:rw
      - qa_node_modules:/app/node_modules:rw
      - /var/run/dbus:/var/run/dbus
    depends_on:
      - webapp
      - server
    environment:
      - BASE_URL=http://localhost:8000
      - NODE_ENV=test
      - JEST_PUPPETEER_CONFIG=puppeteer.config.js
    tmpfs:
      - /tmp
    network_mode: "service:nginx"

  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb
    ports:
      - "27017:27017"

  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: [""]
    command: tail -f /dev/null

volumes:
  qa_node_modules:
  webapp_node_modules:
  server_node_modules: