# docker-compose.override.yml
services:
  webapp:
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./webapp:/app
      - webapp_node_modules:/app/node_modules

  server:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    command: npm run dev
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules

  qa:
    build: ./qa
    privileged: true 
    volumes:
      - ./qa:/app
      - qa_node_modules:/app/node_modules
      - /var/run/dbus:/var/run/dbus
    environment:
      - BASE_URL=http://localhost:8000
      - NODE_ENV=test
      - JEST_PUPPETEER_CONFIG=puppeteer.config.js
    tmpfs:
      - /tmp
    network_mode: "service:nginx"

  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: [""]
    command: tail -f /dev/null

volumes:
  qa_node_modules:
  webapp_node_modules:
  server_node_modules: