# docker-compose.dev.yml (Development overrides)
services:
  app:
    build:
      target: deps
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    
volumes:
  node_modules: